##################################################################################
## This file is part of Kepler's Horizon
##
## Licensed under BSD 3-Clause License
##
## Copyright (c) 2025, sibomots
#################################################################################

# Movement commands
cc_library(
    name = "movement",
    srcs = glob(["*.cpp"]),
    hdrs = ["//app/inc:headers"],
    includes = ["../inc"],
    visibility = ["//visibility:public"],
)
