workspace(name = "keplershorizon")

# MySQL client library
new_local_repository(
    name = "mysql",
    path = "/usr",
    build_file_content = """
cc_library(
    name = "mysqlclient",
    srcs = ["lib/x86_64-linux-gnu/libmysqlclient.so"],
    hdrs = glob(["include/mysql/**/*.h"]),
    includes = ["include/mysql"],
    visibility = ["//visibility:public"],
)
""",
)
