//////////////////////////////////////////////////////////////////////////////////
// This file is part of Kepler's Horizon
//
// Licensed under BSD 3-Clause License
//
// Copyright (c) 2025, sibomots
/////////////////////////////////////////////////////////////////////////////////
#ifndef __CAUSES_FOR_BADNESS_H__
#define __CAUSES_FOR_BADNESS_H__
#include <string>
#include <vector>

// A collection of 300 "causes" for combat perturbations.
// Categories: Personnel, Mechanical, Physics, External, Cyber
const std::vector<std::string> COMBAT_FLAVOR_EVENTS = {
    // --- Personnel / Crew Error ---
    "Ensign Smith didn't report when general quarters was sounded.",
    "The coolant valve was left open during a shift change.",
    "Tactical officer sneezed during the firing sequence.",
    "Navigation sub-routine was accidentally deleted by a cadet.",
    "Captain spilled coffee on the primary console.",
    "Chief Engineer was arguing with the replicator when the alarm rang.",
    "Weapon systems calibration was skipped in the morning report.",
    "Pilot overcorrected for inertial dampener lag.",
    "Sensor operator mistook a glitch for a ghost signature.",
    "Communications officer routed battle comms to the mess hall.",
    "Security team delayed locking down the blast doors.",
    "Medical bay drew too much power for emergency stasis.",
    "Loading mechanism jammed due to improper maintenance.",
    "Targeting scanner was left in diagnostic mode.",
    "Crew fatigue led to a 200ms delay in shield modulation.",
    "A misunderstanding in the chain of command delayed the firing order.",
    "The inertial dampeners were set to 'Training' mode.",
    "A unauthorized game simulation escaped into the tactical grid.",
    "Manual override was engaged by mistake.",
    "The firing key was stuck due to spilled soda.",
    "Crew morale dropped after the last ration reduction.",
    "An argument in the torpedo room delayed loading.",
    "The helmsman was distracted by a hull vibration.",
    "Bridge officers were blinded by a console spark.",
    "Damage control teams were slow to seal deck 4.",
    "The backup gunner fainted under high-G.",
    "A maintenance bot was left inside the jefferies tube.",
    "The captain's log upload saturated the bandwidth.",
    "Shift rotation left the bridge understaffed.",
    "Psych-eval flagged the gunner for hesitation.",
    "The cook used the plasma conduit to heat soup.",
    "A contraband pet chewed through a fiber optic cable.",
    "The deflector dish alignment was eye-balled, not calculated.",
    "Standard operating procedure was ignored for a 'hunch'.",
    "The sensor array was covered in space dust.",
    "Targeting lock was dropped to answer a hail.",
    "The self-destruct cover was loose, causing panic.",
    "A prank involving the gravity generator went wrong.",
    "The life-support buffer overflowed into tactical.",
    "The EVA suit locker door swung open, blocking the corridor.",
    "A rookie rerouted power to the holodeck instead of shields.",
    "The intercom whistled loudly, distracting the commander.",
    "An unsecured crate smashed into the shield generator.",
    "The astrogator misread the star chart.",
    "A biological containment seal leaked into engineering.",
    "The waste extraction system backed up into the bridge.",
    "A crewman was sleepwalking in the torpedo bay.",
    "The XO hesitated to confirm the firing solution.",
    "Maintenance logs were falsified to cover a nap.",
    "The red alert siren malfunctioned and played jazz.",

    // --- Mechanical / Hardware Failure ---
    "Auxiliary power thermal overload reduced PD output.",
    "The magnetic containment bottle flickered.",
    "Gyro-stabilizer sync loss caused a wobble.",
    "Plasma injector manifold cracked under pressure.",
    "The wave-motion conduit de-laminated.",
    "Secondary relays fused during power-up.",
    "Targeting optics fogged up due to humidity.",
    "The antimatter flow regulator seized.",
    "Shield emitters descynchronized by 0.4 terahertz.",
    "The main bus bar vibrated loose.",
    "Thermal exhaust ports were clogged with carbon.",
    "The warp core ejection system armed itself.",
    "Impulse driver coils saturated with tachyon spread.",
    "The Heisenberg compensator failed to compensate.",
    "Gravity plating reversed polarity on deck 9.",
    "The positronic brain experienced a logic cascade.",
    "Neutrino sensors were flooded with white noise.",
    "The EPS conduit ruptured in the starboard nacelle.",
    "Phase discriminators failed to lock.",
    "The tractor beam emitter burned out.",
    "Hull polarization matrix failed to invert.",
    "The structural integrity field collapsed on deck 12.",
    "A micro-fracture in the keel expanded.",
    "The subspace transceiver overheated.",
    "Relays 4 through 10 fused into a solid block.",
    "The plasma venting system triggered early.",
    "Optical data buffers corrupted the targeting file.",
    "The warp field collapsed into a subspace eddy.",
    "Coolant pumps cavitated, causing vibration.",
    "The dilithium crystal cracked.",
    "Reaction control thrusters fired uncommanded.",
    "The main computer core dumped its cache.",
    "Life support scrubbers clogged with ozone.",
    "The holographic targeting interface flickered.",
    "Shield harmonics drifted out of alignment.",
    "The torpedo launch rails warped from heat.",
    "Capacitor banks failed to hold peak charge.",
    "The matter/antimatter mix ratio spiked.",
    "Vector exhaust plates seized in position.",
    "The artificial gravity generator surged.",
    "Sensor pallets locked in forward position.",
    "The docking clamps failed to fully retract.",
    "Power coupling 3A sheered off.", "The backup battery array detonated.",
    "Internal comms failed due to static.", "The hangar bay doors jammed open.",
    "Navigational deflectors overloaded.",
    "The zero-point energy tap fluctuated.",
    "Bio-neural gel packs caught a cold.",
    "The chronometer desynchronized from the fleet.",

    // --- Physics / Anomalies ---
    "A relativistic cosmic ray upset the controller board.",
    "A micro-asteroid deflected off the screen.",
    "Solar flare activity scrambled the sensors.",
    "Local spacetime curvature distorted the targeting beam.",
    "A tachyon burst disrupted the shield grid.",
    "Passed through a cloud of dark matter.",
    "Gravitational shear from a nearby moon.",
    "Quantum foam turbulence reduced engine efficiency.",
    "A subspace rift swallowed the torpedo.",
    "Neutron star radiation interfered with the computer.",
    "Encountered a pocket of null-space.",
    "Time dilation effects desynced the firing clock.",
    "A magnetic storm caused hull magnetization.",
    "Stray gamma burst blinded the sensors.",
    "Hit a resonance frequency with the local nebula.",
    "Spontaneous probability shift caused a miss.",
    "Vacuum fluctuations drained the capacitor.",
    "A wormhole opened and closed in milliseconds.",
    "Dark energy density spiked locally.",
    "Interferometric ghosting caused a phantom target.",
    "A neutrino surge mimicked an enemy launch.",
    "Spatial folding echo doubled the target image.",
    "Gravity waves from a binary system rocked the ship.",
    "A proton storm stripped the outer coating.",
    "Ionic turbulence reduced beam coherence.",
    "Crossed the event horizon of a micro-singularity.",
    "Quantum tunneling bypassed the shield briefly.",
    "A temporal anomaly replayed the last 5 seconds.",
    "Higgs field density fluctuation changed mass.",
    "Subspace harmonic resonance shattered a sensor.",
    "Coronal mass ejection fried the long-range comms.",
    "A rogue planet's gravity well drifted the shot.",
    "Electro-static discharge from space dust.",
    "Vacuum decay was momentarily detected.",
    "Strange matter interaction hardened the hull.",
    "A tachyon eddy spun the ship 180 degrees.",
    "Zero-point fluctuation cooled the core.",
    "Hyper-dimensional bleed-through caused static.",
    "A photon echo confused the rangefinder.",
    "Dark flow pulled the ship off course.",
    "Background radiation spike triggered an alarm.",
    "A quantum entanglement break severed the link.",
    "Space-time drag slowed the impulse drive.",
    "Gravimetric shear tore the solar panels.",
    "A magnetic monopole passed through the bridge.",
    "Vacuum arc discharge shorted the shields.",
    "A superstring snagged the warp nacelle.",
    "Dimensional phase-shift caused a miss.",
    "Entropy gradient reversal healed a distinct scratch.",
    "A virtual particle pair annihilated in the core.",

    // --- Software / Cyber ---
    "Targeting algorithm stuck in an infinite loop.",
    "Firewall updated during combat, blocking the shot.",
    "Enemy ECM flooded the buffer with junk data.",
    "A logic bomb was triggered by the alert status.",
    "The OS decided to defragment the hard drive.",
    "IFF transponder handshake timed out.",
    "A virus uploaded by a probe corrupted the database.",
    "Sensor fusion algorithm diverged.",
    "The encryption key expired mid-battle.",
    "Packet loss on the internal network.",
    "The AI refused to fire on ethical grounds.",
    "Targeting lock-on was spoofed.",
    "Buffer overflow in the weapon control system.",
    "The UI lagged due to high resource usage.",
    "A background update restarted the console.",
    "Telemetry stream was hijacked.",
    "Ghost in the machine rewrote the firing solution.",
    "Signal latency caused a missed timing window.",
    "The database query for 'Enemy' returned 0 results.",
    "A ransomware note appeared on the main screen.",
    "The auto-pilot fought the manual control.",
    "Digital noise filtering removed the actual target.",
    "The translation matrix misinterpreted 'Fire'.",
    "System clock skew caused a sync error.", "The physics engine glitched.",
    "Memory leak crashed the tactical overlay.",
    "The neural net hallucinated a threat.",
    "Cyber-warfare subroutine backfired.", "The comms handshake was rejected.",
    "Data corruption in the friend-or-foe database.",
    "The boot loader corrupted during restart.",
    "A fluctuating power supply caused a bit-flip.",
    "The checksum failed on the firing packet.",
    "Legacy code from 2150 caused a conflict.",
    "The API rate limit was exceeded.",
    "A null pointer exception crashed the turret.",
    "The feedback loop amplified sensor noise.",
    "Encryption overhead slowed the reaction time.",
    "The simulation mode was left active.",
    "The audio driver prioritized music over alerts.",
    "Garbage collection paused the main thread.", "The stack overflowed.",
    "A deadlock occurred in the power distribution.",
    "The rendering engine crashed.", "Inputs were inverted by a glitch.",
    "The fuzzy logic controller was too fuzzy.",
    "A race condition caused the shields to drop.",
    "The navigational mesh failed to load.",
    "Script error: 'target' is undefined.",
    "The mainframe overheat triggered a safe mode.",

    // --- Random / Bizarre ---
    "The ship's cat walked across the control panel.",
    "A micrometeorite punctured the coffee machine.",
    "The vending area depressurized.", "The captain's chair swivel locked up.",
    "A singing anomaly over the comms distracted everyone.",
    "The viewscreen stuck on the rear-view camera.",
    "The gravity turned off for 3 seconds.",
    "The lights went out, then the emergency lights went out.",
    "A hull breach whistled a catchy tune.",
    "The turbo-lift trapped the reinforcements.",
    "A misplaced wrench floated into the beam path.",
    "The distress beacon activated spontaneously.",
    "The toilet flushing caused a pressure drop.",
    "Someone ordered pizza to the bridge.", "The potted plant fell over.",
    "A vivid hallucination of a clown.", "The floor became frictionless.",
    "The air scrubbers released laughing gas.",
    "A rogue cleaning bot scrubbed the targeting lens.",
    "The escape pods launched empty.", "The uniform synthesize malfunctioned.",
    "The blast shield closed on the gunner's fingers.",
    "The snack dispenser launched sodas at high velocity.",
    "The bridge smelled of burning toast.",
    "A localized rainstorm occurred in engineering.",
    "The gravity shifted 90 degrees.", "The ship's mascot escaped its cage.",
    "A temporal hiccup made everyone say 'What?' twice.",
    "The log entries were written in ancient Greek.",
    "The ship decided it was a pacifist.",
    "A ghost of a former captain gave bad advice.",
    "The replicator produced infinite bananas.",
    "The holodeck projected monsters on the bridge.",
    "The universal translator spoke only in rhyme.",
    "The floor turned into lava (holographically).",
    "A swarm of space-bees covered the canopy.",
    "The ship's nameplate fell off.",
    "The external speakers played 'Ride of the Valkyries'.",
    "A giant space-squid looked in the window.",
    "The sensor dish spun continuously.",
    "The landing gear deployed in deep space.", "The ship's horn honked.",
    "All screens displayed static.", "The controls became sticky.",
    "A mysterious humming noise drove the crew mad.",
    "The oxygen mix became too rich.",
    "The artificial night cycle triggered early.",
    "The alarm sound changed to a duck quack.", "The chairs abruptly reclined.",
    "The carpet pattern induced nausea.",

    // --- Expanded Tech / Sci-Fi ---
    "Chroniton particles saturated the hull plating.",
    "The transwarp conduit destabilized.",
    "Subspace transceiver array misaligned.",
    "Dilithium matrix fracture detected.",
    "Plasma coolant leak in the jefferies tube.", "Pattern buffer degradation.",
    "Bussard collectors clogged with interstellar hydrogen.",
    "Gravimetric interference from the singularity.",
    "Tachyon emissions gave away the position.", "Cloaking device power drain.",
    "Deflector shield modulation failure.", "Phaser coil thermal overload.",
    "Photon torpedo guidance lock failure.", "Warp core breach imminent alarm.",
    "Inertial dampener lag.", "Structural integrity field failure.",
    "Bio-neural gel pack infection.", "Isolinesar chip fragmentation.",
    "EPS tap overload.", "Heisenberg compensator glitch.",
    "Universal translator matrix error.",
    "Holodeck safety protocols disengaged.", "Transporter buffer lock loss.",
    "Replicator matrix depletion.", "Tractor beam emitter fused.",
    "Main deflector dish misalignment.", "Auxiliary fusion reactor SCRAM.",
    "Antimatter containment field fluctuation.",
    "Deuterium tank pressure spike.", "Impulse manifold obstruction.",
    "Reaction control system thruster jam.",
    "Navigational sensor array blind spot.",
    "Long-range sensor palette burned out.", "Lateral sensor array ghosting.",
    "Astrometrics lab power failure.", "Stellar cartography update lag.",
    "Exo-biology scanner malfunction.", "Quantum torpedo loading error.",
    "Tri-cobalt device arming failure.", "Plasma torpedo dissipation.",
    "Gravimetric torpedo guidance loss.", "Spatial charge detonation failure.",
    "Minefield IFF handshake error.", "Drone control link severed.",
    "Fighter wing launch rack jam.", "Shuttle bay door seal failure.",
    "Captain's yacht docking latch stuck.", "Escape pod explosive bolt dud.",
    "Airlock outer door seal breach.",
    "Turbolift shaft magnetic field collapse.", "Jefferies tube hatch stuck.",
    "Maintenance conduit plasma fire.", "Environmental control system freeze.",
    "Gravity generator plate crack.", "Sonic shower acoustic feedback.",
    "Food slot dispensing grey goo.", "Synthetic ale fermentation error.",
    "Medical tricorder battery died.", "Hypospray nozzle clogged.",
    "Bio-bed sensor calibration drift.", "Surgical arch power coupling loose.",
    "Stasis field generator fluctuation.", "Quarantine field integrity loss.",
    "Decontamination cycle stuck on rinse.",
    "Emergency forcefield emitter burn out.", "Brig containment field flicker.",
    "Interrogation room camera failure.", "Security phaser charge depletion.",
    "Armory door lock malfunction.", "Photon grenade timer error.",
    "Personal forcefield battery drain.", "EVA suit O2 scrubber failure.",
    "Mag-boot polarity reversal.", "Communicator badge signal loss.",
    "PADD tracking sensitivity drift.", "Viewscreen pixel dead zone.",
    "Bridge console tactile feedback failure.", "Chair restraint system lock.",
    "Lighting panel flicker.", "Carpet static discharge.",
    "Hull plate micro-meteoroid impact.", "Thermal protection tile ablation.",
    "Radiator fin jamming.", "Solar panel retraction failure.",
    "Antenna mast servo motor burnout.", "Running light bulb burnout.",
    "Hull identification number paint peeling.", "Window seal condensation.",
    "Observation lounge glass crack.", "Arboretum plant overgrowth.",
    "Hydroponics bay water leak.", "Cetacean ops tank breach.",
    "Stellar observatory lens cap left on.", "Waste recycling module overflow.",
    "Water purification filter clog.", "Air recycling CO2 scrubber saturation.",
    "Thermal regulation heater coil break.", "Humidity control sensor drift.",
    "Vibration damper spring fatigue.", "Acoustic insulation foam degradation.",
    "Radiation shielding lead lining thinning.",
    "Magnetic shielding polarity flip.", "RFI shielding mesh tear."};

#endif
